# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  name: 'Demo'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  jobs:
    - job: 'BuildClient'
      steps:
      - task: Npm@1
        displayName: 'Install Client Dependencies'
        inputs:
          command: 'install'
          workingDir: 'ClientApp'

      - task: Npm@1
        displayName: 'Build Client Application'
        inputs:
          command: 'ci'
          workingDir: 'ClientApp'
          customCommand: 'run build --prod'

      - task: Npm@1
        displayName: 'Test Client Application'
        inputs:
          command: 'custom'
          workingDir: 'ClientApp'
          customCommand: 'run test --watch=false'

    - job: 'BuildDotNet'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'dotnet build $(buildConfiguration)'

      - script: echo 'Hello World'
        displayName: 'dotnet build $(buildConfiguration)' 

      - task: DotNetCoreCLI@2
        displayName: 'Publish Application'
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(buildConfiguration)  --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
          zipAfterPublish: true

    - job: 'PublishArtifacts'
      steps:
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'